### ISSUE TITLE
Type-o in test spec

### ISSUE THREAD

**Issue by leighsn** [learn-co-curriculum/intro-to-comparison-operators.js#8]
There's an error in the comparison-spec.js file on line 31. "False" should be "true." The test itself is correct-it's just the description of the test that is incorrect.

**Comment by pletcher** [comment]
Fixed https://github.com/learn-co-curriculum/intro-to-comparison-operators.js/commit/10770f7a6904cd8e046f79ebdbde67453a6f115f
