### ISSUE TITLE
Exclamation Point

### ISSUE THREAD

**Issue by NoneOfMaster** [learn-co-curriculum/intro-to-comparison-operators.js#9]
I think it may be that the parenthetical in the last blurb on testTrueStrictEqualityComparison should have (!==) instead of (===) for strict inequality/nonequality

![screen shot 2016-03-24 at 8 14 29 pm](https://cloud.githubusercontent.com/assets/12436033/14037087/4db1c83e-f1fd-11e5-8425-772820474b36.png)

**Comment by AnnJohn** [comment]
thanks for raising this @NoneOfMaster. We'll look into this soon.

**Comment by pletcher** [comment]
The last instructions are kind of subtle, but `1 === parseInt('1')` will definitely return `true`.
